In [2]:
import torch
torch.__version__

'1.8.0'

## Vector

- It is a 1D tensor corresponds to a 1D array. It is a list of tensor elements, or can be considered as a column vector
- It is represented by small letters $x, y, z$


In [6]:
a = torch.arange(5)
a, type(a)

(tensor([0, 1, 2, 3, 4]), torch.Tensor)

## Matrices
- It is a 2D tensor corresponds to a matrix. It is a 2D array of tensor elements. 
- It is represented by capital letters $X, Y, Z$
- Mathematical notation: $A \in R^{m*n}$


In [9]:
A = torch.arange(20).reshape(4, 5)
A, type(A), A.shape, A.size(), len(A)

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 torch.Tensor,
 torch.Size([4, 5]),
 torch.Size([4, 5]),
 4)

## Transpose of a matrix 

In [10]:
A_transpose = A.T
A.shape, A_transpose.shape

(torch.Size([4, 5]), torch.Size([5, 4]))

## Commonly-used Tensor Constructors

In [13]:
torch.ones(2, 4, 5)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [14]:
torch.zeros(2, 4, 5)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [15]:
torch.randn(2, 4, 5)

tensor([[[ 0.0477, -0.9737, -0.0380,  0.0893,  0.9037],
         [-1.1137, -1.6247,  0.1492, -2.1266,  0.9770],
         [ 0.2443, -0.4878,  0.6149,  0.0773,  0.1182],
         [-0.9318, -0.1522, -0.3544,  0.3717,  1.1152]],

        [[-2.3148, -0.5276,  1.2426,  0.0250, -0.8366],
         [ 0.0633,  1.0571, -0.8819,  0.2894, -1.8685],
         [-0.5216,  0.6730,  0.1428,  1.2288, -0.1824],
         [ 0.0847,  0.3545, -1.0089,  1.6480, -0.1725]]])

In [17]:
torch.tensor([[2, 3, 4]])

tensor([[2, 3, 4]])

## Commonly-used Tensor Operators

In [18]:
# Initialising with a type
A = torch.arange(20, dtype=torch.float32).reshape(4, 5)

# Cloning
B = A.clone()

## Element-wise Operations

In [31]:
A + 2, A + 5, (A + 4)/5, A * B, torch.exp(A), A ** 2, torch.pow(A, 4), torch.cos(A)

(tensor([[ 2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11.],
         [12., 13., 14., 15., 16.],
         [17., 18., 19., 20., 21.]]),
 tensor([[ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24.]]),
 tensor([[0.8000, 1.0000, 1.2000, 1.4000, 1.6000],
         [1.8000, 2.0000, 2.2000, 2.4000, 2.6000],
         [2.8000, 3.0000, 3.2000, 3.4000, 3.6000],
         [3.8000, 4.0000, 4.2000, 4.4000, 4.6000]]),
 tensor([[  0.,   1.,   4.,   9.,  16.],
         [ 25.,  36.,  49.,  64.,  81.],
         [100., 121., 144., 169., 196.],
         [225., 256., 289., 324., 361.]]),
 tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
         [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03],
         [2.2026e+04, 5.9874e+04, 1.6275e+05, 4.4241e+05, 1.2026e+06],
         [3.2690e+06, 8.8861e+06, 2.4155e+07, 6.5660e+07, 1.7848e+08]]),
 tensor([[  0.,   1.,   4.,   9.,  16.],
         

In [25]:
A.sum() 

tensor(190.)

In [32]:
# Row-wise summation, Column-wise summation
A.sum(dim=1), A.sum(dim=0)

(tensor([10., 35., 60., 85.]), tensor([30., 34., 38., 42., 46.]))

In [36]:
 # Concatination - row-wise, column-wise
 torch.cat((A, B), dim=0), torch.cat((A, B), dim=1)

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.,  4.,  0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.,  5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14., 10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19., 15., 16., 17., 18., 19.]]))

## Dot Product

- Given two vectors, it calculates the sum over of the products of the elements at the same position
- Given two vectors $x, y \in R^d$ - their dot product will be $x^Ty = \sum_{i=1}^d{x_iy_i}$
- It can also be considered as their weighted sum of a vector for a given set of weights. It comes handly in calculating the regression score.  
    - When the sum of all weights is one, then the dot product is expressed as weighted average
    - After normalising two vectors to have the unit length, the dot product express the cosine of angle between them. It is useful for finding the similarity between two vectors.

In [41]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [47]:
x = torch.arange(5, dtype=torch.float32)
x /= x.sum()
y = torch.randn(5)
y /= y.sum()
x, y, torch.dot(x, y)

(tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000]),
 tensor([ 5.0758,  1.0146, -1.6563, -2.9103, -0.5237]),
 tensor(-1.3124))

## Matrix-Vector Products

- Matrix and vector multiplication is very much like the matrix and matrix multiplication.
- Given a matrix and vector, $A \in R^{m*n}$ and $x \in R^{n}$, the product $Ax$ will be: $Z \in R^{m}$
- Multiplication by $A \in R^{m*n}$ projects vectors from their initial size to the size of the rows of the matrix: $R^n$ -> $R^m$

In [57]:
A = torch.arange(20).reshape(4, -1)
x = torch.arange(5)+1
A.shape, x.shape

(torch.Size([4, 5]), torch.Size([5]))

In [60]:
A, x, torch.mv(A, x)

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([1, 2, 3, 4, 5]),
 tensor([ 40, 115, 190, 265]))

## Matrix-Matrix Multiplication

- In matrix-matrix multiplcation, the dot products of the rows of the first matrix and columns of the second matrix are calculated. Therefore, the number of number of columns in the first matrix should match the number of rows of the second matrix. 
- Assuming two matrices $A \in R^{n*k}$ and $B \in R^{q*j}$, then for multiplcation, k == q. 
- The result of multiplcation of A abd B will be $Z \in R^{n*j}$

In [62]:
A = torch.arange(20).reshape(-1, 5)
B = torch.arange(10).reshape(5, -1)
A, A.shape, B, B.shape

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 torch.Size([4, 5]),
 tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 torch.Size([5, 2]))

In [64]:
Z = torch.mm(A, B)
Z, Z.shape

(tensor([[ 60,  70],
         [160, 195],
         [260, 320],
         [360, 445]]),
 torch.Size([4, 2]))

## Norms

Norms are functions that converts a real or complex vector space to a non-negative real numbers that behaves in a certain way like the distance from the origin. These functions have an origin as zero and are mostly used in comparing numbers. 

- The euclidian distance of a vector from an origin is a norm, call ed the Euclidian norm or 2-norm ($L_1$) which may also be defined as the square root of the inner product of a vector itself. 
$$ ||x||_2 = \sqrt{\sum_{i=1}^n x_i^2}$$
- $L_1$ norm is expressed as the sum of the absolute values of the vector elements. 
$$ ||x||_1 = \sum_{i=1}^n |x_i| $$
- In Deep Learning, norms are used for comparing the model's predictions and the ground-truth values, and try to minimize the distance of the resulting difference from the origin i.e. push the value towards the origin. 

## Broadcasting Mechanism 

In maths, element-wise operation between two tensors can only happen when they both have the same size. However this is not the case with Python and Pytorch. Under certain conditions, even if their shapes differ, we can still perform element-wise operations by invoking the Broadcasting mechanism.

The mechanism first increase the size of one of the tensors by copying elements to match the size of two tensors. Then it performs the element-wise operation. 


In [87]:
A = torch.randn(3, 1).type(torch.int32)+2
C = torch.ones(1, 2).type(torch.int32)
A, C, C + A, A+C

(tensor([[3],
         [2],
         [2]], dtype=torch.int32),
 tensor([[1, 1]], dtype=torch.int32),
 tensor([[4, 4],
         [3, 3],
         [3, 3]], dtype=torch.int32),
 tensor([[4, 4],
         [3, 3],
         [3, 3]], dtype=torch.int32))

## Saving Memory

Running operations can cause allocation of new memory to store the results of some operation instead of reusing existing ones. In Deep Learning, we normally deal with models that contains dozens of parameters and hundreds of rows of data. Taking extra unneccessary storage slow down the process. Therefore, we should do operations in a way that they use the in-place memory, and does not take new memory. 

In [98]:
X = torch.arange(20).type(torch.float32).reshape(5, 4)
Y = 10*X

print("Memory Locations")
old_loc = id(Y)
print(id(X), id(Y))

# New memory operation
Y = Y+X
print(old_loc, id(Y), old_loc == id(Y))
old_loc_2 = id(Y)

# In-place operation
Y += X
print(old_loc_2, id(Y), old_loc_2==id(Y))


Memory Locations
140304602130752 140304602131776
140304602131776 140304662056000 False
140304662056000 140304662056000 True
